# Generated by Django 4.1.2 on 2022-10-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo1', models.CharField(max_length=250, verbose_name='Titulo de contato')),
                ('whatsapp', models.CharField(max_length=250, verbose_name='Whatsapp')),
                ('instagram', models.CharField(max_length=250, verbose_name='Instagram')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('localizacao', models.CharField(max_length=250, verbose_name='Localização')),
            ],
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=12)),
                ('mensagem', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Inicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='fotos', verbose_name='Imagem da logo')),
                ('titulo1', models.CharField(max_length=250, verbose_name='Titulo inicial parte 1')),
                ('titulo2', models.CharField(max_length=250, verbose_name='Titulo inicial parte 2')),
                ('descricao1', models.TextField(default='', max_length=500, verbose_name='Mensagem de efeito parte 1')),
                ('descricao2', models.TextField(default='', max_length=500, verbose_name='Mensagem de efeito parte 2')),
                ('text_button', models.CharField(max_length=100, verbose_name='Texto-Botão')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='Titulo de Portfólio')),
                ('image1', models.ImageField(upload_to='fotos', verbose_name='Imagem 1')),
                ('image2', models.ImageField(upload_to='fotos', verbose_name='Imagem 2')),
                ('image3', models.ImageField(upload_to='fotos', verbose_name='Imagem 3')),
                ('image4', models.ImageField(upload_to='fotos', verbose_name='Imagem 4')),
                ('image5', models.ImageField(upload_to='fotos', verbose_name='Imagem 5')),
                ('image6', models.ImageField(upload_to='fotos', verbose_name='Imagem 6')),
                ('comentario1', models.TextField(max_length=250, verbose_name='Comentario 1')),
                ('autor1', models.CharField(max_length=50, verbose_name='Autor 1')),
                ('comentario2', models.TextField(max_length=250, verbose_name='Comentario 2')),
                ('autor2', models.CharField(max_length=50, verbose_name='Autor 2')),
                ('comentario3', models.TextField(max_length=250, verbose_name='Comentario 3')),
                ('autor3', models.CharField(max_length=50, verbose_name='Autor 3')),
                ('comentario4', models.TextField(max_length=250, verbose_name='Comentario 4')),
                ('autor4', models.CharField(max_length=50, verbose_name='Autor 4')),
            ],
        ),
        migrations.CreateModel(
            name='QuemSomos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='Titulo de Quem Somos')),
                ('image', models.ImageField(upload_to='fotos', verbose_name='Imagem')),
                ('descricao1', models.TextField(default='', max_length=250, verbose_name='Descrição de Quem Somos parte 1')),
                ('descricao2', models.TextField(default='', max_length=250, verbose_name='Descrição de Quem Somos parte 2')),
            ],
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='Titulo de Serviços')),
                ('descricao1', models.TextField(default='', max_length=250, verbose_name='Descrição para decoração')),
                ('descricao2', models.TextField(default='', max_length=250, verbose_name='Descrição para Segurança')),
                ('descricao3', models.TextField(default='', max_length=250, verbose_name='Descrição de Logistica')),
                ('descricao4', models.TextField(default='', max_length=250, verbose_name='Descrição de Comercialização')),
                ('descricao5', models.TextField(default='', max_length=250, verbose_name='Descrição de Planejamento')),
                ('descricao6', models.TextField(default='', max_length=250, verbose_name='Descrição de Infraestrutura')),
            ],
        ),
    ]
